name: mvn clean test

on: push

jobs:
  mvn-clean-test:
    name: Mvn clean test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Mvn clean test
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Build with maven
        run: mvn --batch-mode --update-snapshots package
